### ISSUE TITLE
mac version missing for v0.5

### ISSUE THREAD

**Issue by adrian-schnell** [saiive/defimnsigner#2]
for version v0.5 the mac version was not compiled.

**Comment by dpfaffenbauer** [comment]
we know :), will do that in a couple of hours

**Comment by adrian-schnell** [comment]
ah i see... 
think I was reacting too quickly :D

**Comment by dpfaffenbauer** [comment]
@adrian-schnell it is now available: https://github.com/saiive/defimnsigner/releases/tag/0.5
