### ISSUE TITLE
program gets stuck .  loading masternodes ....

### ISSUE THREAD

**Issue by KermitIsBack** [saiive/defimnsigner#3]
After setting the credentials and starting the wallet app the program gets stuck without message.
It is displaying loading masternodes .... and the circle is turning endless.

**Comment by dpfaffenbauer** [comment]
Windows or Mac?

**Comment by KermitIsBack** [comment]
Mac
Problem just solved , my credentials were wrong. Thank you for you help.

**Comment by dpfaffenbauer** [comment]
👍 we‘ll make usability better anyway. Thanks for letting us know
